### ISSUE TITLE
createNewWallet error : 'Byte string exceeds maximum size' 

### ISSUE THREAD

**Issue by lennip** [blocktrail/blocktrail-sdk-php#42]
Hello,

I have a problem with the latest version of Blocktrail SDK.
I follow the API documentation examples to create a wallet programmatically like so:

$client = new BlocktrailSDK($myAPIKEY, $myAPISECRET, "BTC", true);
list($wallet, $primaryMnemonic, $backupMnemonic, $blocktrailPublicKeys) = $client->createNewWallet("mytestwallet", "securepasswordgoeshere");   

I get the following PHP error related to BIP32:
Fatal error: Uncaught exception 'Exception' with message 'Byte string exceeds maximum size' in ....\vendor\bitwasp\buffertools\src\Buffertools\Buffer.php on line 38

I have PHP 5.6.25, Apache 2.4.23, and Windows 10 64bits, and all required PHP extensions enabled. 

![phpblocktrail](https://cloud.githubusercontent.com/assets/2891053/21361869/30bca744-c6e6-11e6-8efb-a5056ee85266.jpg)

**Comment by afk11** [comment]
It's possible the XAMP build itself could be 32-bit and is causing this. Can you paste the output of `echo PHP_INT_MAX`?

**Comment by rubensayshi** [comment]
@lennip it seems XAMPP for windows is 32bit and has not 64bit version, there's some incompatibility issues with the underlying libs we use that don't support 32bit because for example BIP32 requires 64bit ints.

considering how treacherous 32bit can be we unfortunately don't intend to support 32bit ..

I recommend you use docker to develop PHP applications in windows (regardless of the above issue) to mimic a linux based host (I asume you host on linux, not on windows).
